services:
  - type: web
    name: clinique-chatbot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8002
    envVars:
      - key: PORT
        value: 8002
